// Permission and role related constants

export const USER_ROLES = {
  SUPER_ADMIN: 'super_admin',
  ADMIN: 'admin',
  MANAGER: 'manager',
  COORDINATOR: 'coordinator',
  OPERATOR: 'operator',
  VIEWER: 'viewer'
} as const;

export const ROLE_HIERARCHY = {
  [USER_ROLES.SUPER_ADMIN]: 6,
  [USER_ROLES.ADMIN]: 5,
  [USER_ROLES.MANAGER]: 4,
  [USER_ROLES.COORDINATOR]: 3,
  [USER_ROLES.OPERATOR]: 2,
  [USER_ROLES.VIEWER]: 1
} as const;

export const ROLE_DESCRIPTIONS = {
  [USER_ROLES.SUPER_ADMIN]: 'Tüm sistem yetkilerine sahip süper yönetici',
  [USER_ROLES.ADMIN]: 'Sistem yönetimi hariç tüm yetkiler',
  [USER_ROLES.MANAGER]: 'Operasyonel yönetim yetkileri',
  [USER_ROLES.COORDINATOR]: 'Koordinasyon ve takip yetkileri',
  [USER_ROLES.OPERATOR]: 'Temel işlem yetkileri',
  [USER_ROLES.VIEWER]: 'Sadece görüntüleme yetkisi'
} as const;

export const PERMISSIONS = {
  // System permissions
  SYSTEM_ADMIN: 'system:admin',
  SYSTEM_SETTINGS: 'system:settings',
  SYSTEM_LOGS: 'system:logs',
  SYSTEM_BACKUP: 'system:backup',
  
  // User management
  USERS_VIEW: 'users:view',
  USERS_CREATE: 'users:create',
  USERS_EDIT: 'users:edit',
  USERS_DELETE: 'users:delete',
  USERS_PERMISSIONS: 'users:permissions',
  
  // Beneficiaries
  BENEFICIARIES_VIEW: 'beneficiaries:view',
  BENEFICIARIES_CREATE: 'beneficiaries:create',
  BENEFICIARIES_EDIT: 'beneficiaries:edit',
  BENEFICIARIES_DELETE: 'beneficiaries:delete',
  BENEFICIARIES_EXPORT: 'beneficiaries:export',
  BENEFICIARIES_IMPORT: 'beneficiaries:import',
  
  // Applications
  APPLICATIONS_VIEW: 'applications:view',
  APPLICATIONS_CREATE: 'applications:create',
  APPLICATIONS_EDIT: 'applications:edit',
  APPLICATIONS_DELETE: 'applications:delete',
  APPLICATIONS_APPROVE: 'applications:approve',
  APPLICATIONS_REJECT: 'applications:reject',
  
  // Aid Records
  AID_RECORDS_VIEW: 'aid_records:view',
  AID_RECORDS_CREATE: 'aid_records:create',
  AID_RECORDS_EDIT: 'aid_records:edit',
  AID_RECORDS_DELETE: 'aid_records:delete',
  
  // Payments
  PAYMENTS_VIEW: 'payments:view',
  PAYMENTS_CREATE: 'payments:create',
  PAYMENTS_EDIT: 'payments:edit',
  PAYMENTS_DELETE: 'payments:delete',
  PAYMENTS_PROCESS: 'payments:process',
  PAYMENTS_CANCEL: 'payments:cancel',
  
  // Documents
  DOCUMENTS_VIEW: 'documents:view',
  DOCUMENTS_UPLOAD: 'documents:upload',
  DOCUMENTS_DOWNLOAD: 'documents:download',
  DOCUMENTS_DELETE: 'documents:delete',
  
  // Reports
  REPORTS_VIEW: 'reports:view',
  REPORTS_GENERATE: 'reports:generate',
  REPORTS_EXPORT: 'reports:export',
  
  // Donations
  DONATIONS_VIEW: 'donations:view',
  DONATIONS_CREATE: 'donations:create',
  DONATIONS_EDIT: 'donations:edit',
  DONATIONS_DELETE: 'donations:delete',
  
  // Messages
  MESSAGES_VIEW: 'messages:view',
  MESSAGES_SEND: 'messages:send',
  MESSAGES_BULK_SEND: 'messages:bulk_send',
  MESSAGES_TEMPLATES: 'messages:templates',
  
  // Definitions
  DEFINITIONS_VIEW: 'definitions:view',
  DEFINITIONS_EDIT: 'definitions:edit'
} as const;

export const ROLE_PERMISSIONS = {
  [USER_ROLES.SUPER_ADMIN]: [
    // All permissions
    ...Object.values(PERMISSIONS)
  ],
  
  [USER_ROLES.ADMIN]: [
    // All except system admin
    PERMISSIONS.SYSTEM_SETTINGS,
    PERMISSIONS.SYSTEM_LOGS,
    PERMISSIONS.USERS_VIEW,
    PERMISSIONS.USERS_CREATE,
    PERMISSIONS.USERS_EDIT,
    PERMISSIONS.USERS_DELETE,
    PERMISSIONS.USERS_PERMISSIONS,
    PERMISSIONS.BENEFICIARIES_VIEW,
    PERMISSIONS.BENEFICIARIES_CREATE,
    PERMISSIONS.BENEFICIARIES_EDIT,
    PERMISSIONS.BENEFICIARIES_DELETE,
    PERMISSIONS.BENEFICIARIES_EXPORT,
    PERMISSIONS.BENEFICIARIES_IMPORT,
    PERMISSIONS.APPLICATIONS_VIEW,
    PERMISSIONS.APPLICATIONS_CREATE,
    PERMISSIONS.APPLICATIONS_EDIT,
    PERMISSIONS.APPLICATIONS_DELETE,
    PERMISSIONS.APPLICATIONS_APPROVE,
    PERMISSIONS.APPLICATIONS_REJECT,
    PERMISSIONS.AID_RECORDS_VIEW,
    PERMISSIONS.AID_RECORDS_CREATE,
    PERMISSIONS.AID_RECORDS_EDIT,
    PERMISSIONS.AID_RECORDS_DELETE,
    PERMISSIONS.PAYMENTS_VIEW,
    PERMISSIONS.PAYMENTS_CREATE,
    PERMISSIONS.PAYMENTS_EDIT,
    PERMISSIONS.PAYMENTS_DELETE,
    PERMISSIONS.PAYMENTS_PROCESS,
    PERMISSIONS.PAYMENTS_CANCEL,
    PERMISSIONS.DOCUMENTS_VIEW,
    PERMISSIONS.DOCUMENTS_UPLOAD,
    PERMISSIONS.DOCUMENTS_DOWNLOAD,
    PERMISSIONS.DOCUMENTS_DELETE,
    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.REPORTS_GENERATE,
    PERMISSIONS.REPORTS_EXPORT,
    PERMISSIONS.DONATIONS_VIEW,
    PERMISSIONS.DONATIONS_CREATE,
    PERMISSIONS.DONATIONS_EDIT,
    PERMISSIONS.DONATIONS_DELETE,
    PERMISSIONS.MESSAGES_VIEW,
    PERMISSIONS.MESSAGES_SEND,
    PERMISSIONS.MESSAGES_BULK_SEND,
    PERMISSIONS.MESSAGES_TEMPLATES,
    PERMISSIONS.DEFINITIONS_VIEW,
    PERMISSIONS.DEFINITIONS_EDIT
  ],
  
  [USER_ROLES.MANAGER]: [
    PERMISSIONS.USERS_VIEW,
    PERMISSIONS.BENEFICIARIES_VIEW,
    PERMISSIONS.BENEFICIARIES_CREATE,
    PERMISSIONS.BENEFICIARIES_EDIT,
    PERMISSIONS.BENEFICIARIES_EXPORT,
    PERMISSIONS.APPLICATIONS_VIEW,
    PERMISSIONS.APPLICATIONS_CREATE,
    PERMISSIONS.APPLICATIONS_EDIT,
    PERMISSIONS.APPLICATIONS_APPROVE,
    PERMISSIONS.APPLICATIONS_REJECT,
    PERMISSIONS.AID_RECORDS_VIEW,
    PERMISSIONS.AID_RECORDS_CREATE,
    PERMISSIONS.AID_RECORDS_EDIT,
    PERMISSIONS.PAYMENTS_VIEW,
    PERMISSIONS.PAYMENTS_CREATE,
    PERMISSIONS.PAYMENTS_EDIT,
    PERMISSIONS.PAYMENTS_PROCESS,
    PERMISSIONS.DOCUMENTS_VIEW,
    PERMISSIONS.DOCUMENTS_UPLOAD,
    PERMISSIONS.DOCUMENTS_DOWNLOAD,
    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.REPORTS_GENERATE,
    PERMISSIONS.DONATIONS_VIEW,
    PERMISSIONS.DONATIONS_CREATE,
    PERMISSIONS.DONATIONS_EDIT,
    PERMISSIONS.MESSAGES_VIEW,
    PERMISSIONS.MESSAGES_SEND,
    PERMISSIONS.MESSAGES_BULK_SEND,
    PERMISSIONS.DEFINITIONS_VIEW
  ],
  
  [USER_ROLES.COORDINATOR]: [
    PERMISSIONS.BENEFICIARIES_VIEW,
    PERMISSIONS.BENEFICIARIES_CREATE,
    PERMISSIONS.BENEFICIARIES_EDIT,
    PERMISSIONS.APPLICATIONS_VIEW,
    PERMISSIONS.APPLICATIONS_CREATE,
    PERMISSIONS.APPLICATIONS_EDIT,
    PERMISSIONS.AID_RECORDS_VIEW,
    PERMISSIONS.AID_RECORDS_CREATE,
    PERMISSIONS.PAYMENTS_VIEW,
    PERMISSIONS.DOCUMENTS_VIEW,
    PERMISSIONS.DOCUMENTS_UPLOAD,
    PERMISSIONS.DOCUMENTS_DOWNLOAD,
    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.DONATIONS_VIEW,
    PERMISSIONS.MESSAGES_VIEW,
    PERMISSIONS.MESSAGES_SEND,
    PERMISSIONS.DEFINITIONS_VIEW
  ],
  
  [USER_ROLES.OPERATOR]: [
    PERMISSIONS.BENEFICIARIES_VIEW,
    PERMISSIONS.BENEFICIARIES_CREATE,
    PERMISSIONS.APPLICATIONS_VIEW,
    PERMISSIONS.APPLICATIONS_CREATE,
    PERMISSIONS.AID_RECORDS_VIEW,
    PERMISSIONS.PAYMENTS_VIEW,
    PERMISSIONS.DOCUMENTS_VIEW,
    PERMISSIONS.DOCUMENTS_UPLOAD,
    PERMISSIONS.DOCUMENTS_DOWNLOAD,
    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.DONATIONS_VIEW,
    PERMISSIONS.MESSAGES_VIEW,
    PERMISSIONS.DEFINITIONS_VIEW
  ],
  
  [USER_ROLES.VIEWER]: [
    PERMISSIONS.BENEFICIARIES_VIEW,
    PERMISSIONS.APPLICATIONS_VIEW,
    PERMISSIONS.AID_RECORDS_VIEW,
    PERMISSIONS.PAYMENTS_VIEW,
    PERMISSIONS.DOCUMENTS_VIEW,
    PERMISSIONS.DOCUMENTS_DOWNLOAD,
    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.DONATIONS_VIEW,
    PERMISSIONS.MESSAGES_VIEW,
    PERMISSIONS.DEFINITIONS_VIEW
  ]
} as const;

export const PERMISSION_GROUPS = {
  SYSTEM: {
    name: 'Sistem Yönetimi',
    permissions: [
      PERMISSIONS.SYSTEM_ADMIN,
      PERMISSIONS.SYSTEM_SETTINGS,
      PERMISSIONS.SYSTEM_LOGS,
      PERMISSIONS.SYSTEM_BACKUP
    ]
  },
  USERS: {
    name: 'Kullanıcı Yönetimi',
    permissions: [
      PERMISSIONS.USERS_VIEW,
      PERMISSIONS.USERS_CREATE,
      PERMISSIONS.USERS_EDIT,
      PERMISSIONS.USERS_DELETE,
      PERMISSIONS.USERS_PERMISSIONS
    ]
  },
  BENEFICIARIES: {
    name: 'İhtiyaç Sahipleri',
    permissions: [
      PERMISSIONS.BENEFICIARIES_VIEW,
      PERMISSIONS.BENEFICIARIES_CREATE,
      PERMISSIONS.BENEFICIARIES_EDIT,
      PERMISSIONS.BENEFICIARIES_DELETE,
      PERMISSIONS.BENEFICIARIES_EXPORT,
      PERMISSIONS.BENEFICIARIES_IMPORT
    ]
  },
  APPLICATIONS: {
    name: 'Başvurular',
    permissions: [
      PERMISSIONS.APPLICATIONS_VIEW,
      PERMISSIONS.APPLICATIONS_CREATE,
      PERMISSIONS.APPLICATIONS_EDIT,
      PERMISSIONS.APPLICATIONS_DELETE,
      PERMISSIONS.APPLICATIONS_APPROVE,
      PERMISSIONS.APPLICATIONS_REJECT
    ]
  },
  AID_RECORDS: {
    name: 'Yardım Kayıtları',
    permissions: [
      PERMISSIONS.AID_RECORDS_VIEW,
      PERMISSIONS.AID_RECORDS_CREATE,
      PERMISSIONS.AID_RECORDS_EDIT,
      PERMISSIONS.AID_RECORDS_DELETE
    ]
  },
  PAYMENTS: {
    name: 'Ödemeler',
    permissions: [
      PERMISSIONS.PAYMENTS_VIEW,
      PERMISSIONS.PAYMENTS_CREATE,
      PERMISSIONS.PAYMENTS_EDIT,
      PERMISSIONS.PAYMENTS_DELETE,
      PERMISSIONS.PAYMENTS_PROCESS,
      PERMISSIONS.PAYMENTS_CANCEL
    ]
  },
  DOCUMENTS: {
    name: 'Belgeler',
    permissions: [
      PERMISSIONS.DOCUMENTS_VIEW,
      PERMISSIONS.DOCUMENTS_UPLOAD,
      PERMISSIONS.DOCUMENTS_DOWNLOAD,
      PERMISSIONS.DOCUMENTS_DELETE
    ]
  },
  REPORTS: {
    name: 'Raporlar',
    permissions: [
      PERMISSIONS.REPORTS_VIEW,
      PERMISSIONS.REPORTS_GENERATE,
      PERMISSIONS.REPORTS_EXPORT
    ]
  },
  DONATIONS: {
    name: 'Bağışlar',
    permissions: [
      PERMISSIONS.DONATIONS_VIEW,
      PERMISSIONS.DONATIONS_CREATE,
      PERMISSIONS.DONATIONS_EDIT,
      PERMISSIONS.DONATIONS_DELETE
    ]
  },
  MESSAGES: {
    name: 'Mesajlar',
    permissions: [
      PERMISSIONS.MESSAGES_VIEW,
      PERMISSIONS.MESSAGES_SEND,
      PERMISSIONS.MESSAGES_BULK_SEND,
      PERMISSIONS.MESSAGES_TEMPLATES
    ]
  },
  DEFINITIONS: {
    name: 'Tanımlamalar',
    permissions: [
      PERMISSIONS.DEFINITIONS_VIEW,
      PERMISSIONS.DEFINITIONS_EDIT
    ]
  }
} as const;

export const PERMISSION_DESCRIPTIONS = {
  [PERMISSIONS.SYSTEM_ADMIN]: 'Sistem yöneticisi yetkisi',
  [PERMISSIONS.SYSTEM_SETTINGS]: 'Sistem ayarlarını düzenleme',
  [PERMISSIONS.SYSTEM_LOGS]: 'Sistem loglarını görüntüleme',
  [PERMISSIONS.SYSTEM_BACKUP]: 'Sistem yedekleme işlemleri',
  
  [PERMISSIONS.USERS_VIEW]: 'Kullanıcıları görüntüleme',
  [PERMISSIONS.USERS_CREATE]: 'Yeni kullanıcı oluşturma',
  [PERMISSIONS.USERS_EDIT]: 'Kullanıcı bilgilerini düzenleme',
  [PERMISSIONS.USERS_DELETE]: 'Kullanıcı silme',
  [PERMISSIONS.USERS_PERMISSIONS]: 'Kullanıcı yetkilerini yönetme',
  
  [PERMISSIONS.BENEFICIARIES_VIEW]: 'İhtiyaç sahiplerini görüntüleme',
  [PERMISSIONS.BENEFICIARIES_CREATE]: 'Yeni ihtiyaç sahibi ekleme',
  [PERMISSIONS.BENEFICIARIES_EDIT]: 'İhtiyaç sahibi bilgilerini düzenleme',
  [PERMISSIONS.BENEFICIARIES_DELETE]: 'İhtiyaç sahibi silme',
  [PERMISSIONS.BENEFICIARIES_EXPORT]: 'İhtiyaç sahipleri listesini dışa aktarma',
  [PERMISSIONS.BENEFICIARIES_IMPORT]: 'İhtiyaç sahipleri listesini içe aktarma'
} as const;